### ISSUE TITLE
Could not find project language_det_eval

### ISSUE THREAD

**Issue by twangnh** [liunian-harold-li/DesCo#3]
```
Traceback (most recent call last):
  File "tools/test_net_omnilabel.py", line 637, in <module>
    main()
  File "tools/test_net_omnilabel.py", line 339, in main
    for run in runs:
  File "/root/miniconda3/envs/new/lib/python3.7/site-packages/wandb/apis/public.py", line 1261, in __next__
    if not self._load_page():
  File "/root/miniconda3/envs/new/lib/python3.7/site-packages/wandb/apis/public.py", line 1248, in _load_page
    self.objects.extend(self.convert_objects())
  File "/root/miniconda3/envs/new/lib/python3.7/site-packages/wandb/apis/public.py", line 1815, in convert_objects
    raise ValueError("Could not find project %s" % self.project)
ValueError: Could not find project language_det_eval
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 55673) of binary: /root/miniconda3/envs/new/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
```
got the following error when running desco_glip evaluation on omnilabel

`python -m torch.distributed.launch --master_port 6006 --nproc_per_node=1 tools/test_net_omnilabel.py --config-file configs/pretrain_new/desco_glip.yaml --weight outputs/GLIP/desco_glip_tiny.pth --task_config configs/omnilabel/omnilabel_val_eval.yaml --chunk_size 20 OUTPUT_DIR outputs/eval_omnilabel TEST.IMS_PER_BATCH 1 DATASETS.TEST "('omnilabel_val_coco',)"`

could you please help

**Comment by liunian-harold-li** [comment]
Sorry this error was because I forgot to comment out the part where we sync the results to weight and biases (an experiment logging tool).

I have committed a change to fix the issue.
